from __future__ import annotations
from sqlalchemy import ForeignKey

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, uuid_pk

if TYPE_CHECKING:
    from app.models.user import User


class Department(Base):
    """Organisational unit a user belongs to (e.g. Cyber Crime Cell, FSL)."""

    __tablename__ = "departments"

    id: Mapped[uuid.UUID] = uuid_pk()
    name: Mapped[str] = mapped_column(String(128), unique=True, nullable=False, index=True)
    description: Mapped[str | None] = mapped_column(String(512))
    
    parent_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("departments.id", ondelete="RESTRICT"), nullable=True, index=True)
    org_type: Mapped[str] = mapped_column(String(32), default="UNIT", nullable=False)
    path: Mapped[str] = mapped_column(String(255), default="/", nullable=False, index=True)

    users: Mapped[list["User"]] = relationship(back_populates="department")
    parent: Mapped["Department | None"] = relationship(remote_side=[id])

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Department {self.name}>"

from sqlalchemy import event
from sqlalchemy.orm import Session

@event.listens_for(Department, 'before_insert')
def receive_before_insert(mapper, connection, target):
    # We don't have target.id yet if it's generated by DB, but we use uuid_pk with default=uuid.uuid4
    # Let's ensure target.id exists
    if not target.id:
        import uuid
        target.id = uuid.uuid4()
    
    if target.parent_id:
        # Fetch parent
        parent = connection.execute(
            mapper.local_table.select().where(mapper.local_table.c.id == target.parent_id)
        ).first()
        if parent:
            target.path = f"{parent.path}{target.id}/"
        else:
            target.path = f"/{target.id}/"
    else:
        target.path = f"/{target.id}/"

@event.listens_for(Department, 'before_update')
def receive_before_update(mapper, connection, target):
    # Realistically changing parents requires updating all children's paths.
    # We will just update this node's path. Handling full tree moves is complex.
    if target.parent_id:
        parent = connection.execute(
            mapper.local_table.select().where(mapper.local_table.c.id == target.parent_id)
        ).first()
        if parent:
            new_path = f"{parent.path}{target.id}/"
            target.path = new_path
    else:
        target.path = f"/{target.id}/"
