"""blockchain_anchor

Revision ID: 451519f9902b
Revises: 1e3c75dd8878
Create Date: 2026-09-10 15:54:19.884281
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '451519f9902b'
down_revision: Union[str, None] = '1e3c75dd8878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_anchors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('anchored_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANCHORED', 'FAILED', name='anchorstatus'), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('contract_address', sa.String(length=42), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_blockchain_anchors_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_anchors')),
    sa.UniqueConstraint('document_version_id', name=op.f('uq_blockchain_anchors_document_version_id'))
    )


    op.execute("ALTER TABLE audit_events DROP CONSTRAINT IF EXISTS audit_events_action_check")
    op.execute(
        "ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check CHECK "
        "(action IN ('LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'USER_CREATED', 'CASE_CREATED', "
        "'CASE_VIEWED', 'CASE_STATUS_CHANGED', 'CASE_ACCESS_DENIED', 'CASE_MEMBER_ASSIGNED', "
        "'DOCUMENT_UPLOADED', 'DOCUMENT_VERSION_CREATED', 'DOCUMENT_DOWNLOADED', "
        "'DOCUMENT_INTEGRITY_VERIFIED', 'DOCUMENT_INTEGRITY_FAILED', 'UPLOAD_REJECTED', "
        "'EVIDENCE_CREATED', 'EVIDENCE_SEALED', 'EVIDENCE_TRANSFER_CREATED', "
        "'EVIDENCE_TRANSFER_ACCEPTED', 'EVIDENCE_TRANSFER_REJECTED', 'EVIDENCE_ANALYSIS_STARTED', "
        "'EVIDENCE_ANALYSIS_COMPLETED', 'EVIDENCE_COURT_SUBMITTED', 'EVIDENCE_ARCHIVED', "
        "'EVIDENCE_INTEGRITY_VERIFIED', 'EVIDENCE_ACCESS_DENIED', 'SEARCH_PERFORMED', 'ANCHOR_ATTEMPTED'))"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('blockchain_anchors')
    # ### end Alembic commands ###
