"""Add court portal

Revision ID: c051e77cd4c7
Revises: 2ecea4013bff
Create Date: 2026-09-11 13:09:25.053602
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c051e77cd4c7'
down_revision: Union[str, None] = '2ecea4013bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_access_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REDEEMED', 'EXPIRED', 'REVOKED', name='courtaccessstatus', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_court_access_grants_case_id_cases')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_court_access_grants_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_access_grants'))
    )
    op.create_index(op.f('ix_court_access_grants_case_id'), 'court_access_grants', ['case_id'], unique=False)
    op.create_index(op.f('ix_court_access_grants_reference'), 'court_access_grants', ['reference'], unique=True)
    op.add_column('audit_events', sa.Column('court_grant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_court_grant_id'), 'audit_events', ['court_grant_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_court_grant_id_court_access_grants'), 'audit_events', 'court_access_grants', ['court_grant_id'], ['id'], ondelete='RESTRICT')


    # Recreate chk_audit_attribution
    op.execute("ALTER TABLE audit_events DROP CONSTRAINT IF EXISTS chk_audit_attribution")
    op.create_check_constraint('chk_audit_attribution', 'audit_events', "actor_id IS NOT NULL OR court_grant_id IS NOT NULL OR action = 'LOGIN_FAILED'")
    
    # Update case_status constraint
    op.execute("ALTER TABLE cases DROP CONSTRAINT IF EXISTS case_status_check")
    op.execute("ALTER TABLE cases DROP CONSTRAINT IF EXISTS ck_cases_case_status")
    op.execute(
        "ALTER TABLE cases ADD CONSTRAINT case_status_check CHECK "
        "(status IN ('OPEN', 'UNDER_INVESTIGATION', 'SUBMITTED', 'UNDER_TRIAL', 'CLOSED', 'ARCHIVED'))"
    )

    # Update audit_events_action_check
    op.execute("ALTER TABLE audit_events DROP CONSTRAINT IF EXISTS audit_events_action_check")
    op.execute(
        "ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check CHECK "
        "(action IN ('LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'USER_CREATED', 'USER_MODIFIED', 'DEPARTMENT_MODIFIED', 'CASE_CREATED', "
        "'CASE_VIEWED', 'CASE_STATUS_CHANGED', 'CASE_ACCESS_DENIED', 'CASE_MEMBER_ASSIGNED', "
        "'DOCUMENT_UPLOADED', 'DOCUMENT_VERSION_CREATED', 'DOCUMENT_DOWNLOADED', "
        "'DOCUMENT_INTEGRITY_VERIFIED', 'DOCUMENT_INTEGRITY_FAILED', 'UPLOAD_REJECTED', "
        "'EVIDENCE_CREATED', 'EVIDENCE_SEALED', 'EVIDENCE_TRANSFER_CREATED', "
        "'EVIDENCE_TRANSFER_ACCEPTED', 'EVIDENCE_TRANSFER_REJECTED', 'EVIDENCE_ANALYSIS_STARTED', "
        "'EVIDENCE_ANALYSIS_COMPLETED', 'EVIDENCE_COURT_SUBMITTED', 'EVIDENCE_ARCHIVED', "
        "'EVIDENCE_INTEGRITY_VERIFIED', 'EVIDENCE_ACCESS_DENIED', 'SEARCH_PERFORMED', 'ANCHOR_ATTEMPTED', "
        "'COURT_ACCESS_GRANTED', 'COURT_ACCESS_REDEEMED', 'COURT_CASE_VIEWED', 'COURT_DOCUMENT_VIEWED', 'COURT_VERIFY_REQUESTED'))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('fk_audit_events_court_grant_id_court_access_grants'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_court_grant_id'), table_name='audit_events')
    op.drop_column('audit_events', 'court_grant_id')
    op.drop_index(op.f('ix_court_access_grants_reference'), table_name='court_access_grants')
    op.drop_index(op.f('ix_court_access_grants_case_id'), table_name='court_access_grants')
    op.drop_table('court_access_grants')
    # ### end Alembic commands ###
