"""org_hierarchy

Revision ID: dd14912ac6e8
Revises: 0bbb137c1c07
Create Date: 2026-08-31 10:10:17.736481
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd14912ac6e8'
down_revision: Union[str, None] = '0bbb137c1c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable first
    op.add_column('cases', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cases_department_id'), 'cases', ['department_id'], unique=False)
    op.create_foreign_key(op.f('fk_cases_department_id_departments'), 'cases', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.add_column('departments', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('departments', sa.Column('org_type', sa.String(length=32), nullable=True))
    op.add_column('departments', sa.Column('path', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_departments_path'), 'departments', ['path'], unique=False)
    op.create_foreign_key(op.f('fk_departments_parent_id_departments'), 'departments', 'departments', ['parent_id'], ['id'], ondelete='RESTRICT')

    # Backfill departments
    op.execute("UPDATE departments SET org_type = 'UNIT', path = '/' || id::text || '/'")
    op.alter_column('departments', 'org_type', nullable=False)
    op.alter_column('departments', 'path', nullable=False)

    # Backfill cases
    op.execute("""
        UPDATE cases SET department_id = (
            SELECT department_id FROM users WHERE id = cases.created_by
        )
    """)
    # If any cases don't have a department (e.g. created_by is null or user has no department), assign to first available
    op.execute("""
        UPDATE cases SET department_id = (SELECT id FROM departments LIMIT 1) WHERE department_id IS NULL
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_departments_parent_id_departments'), 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_path'), table_name='departments')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_column('departments', 'path')
    op.drop_column('departments', 'org_type')
    op.drop_column('departments', 'parent_id')
    op.drop_constraint(op.f('fk_cases_department_id_departments'), 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_department_id'), table_name='cases')
    op.drop_column('cases', 'department_id')
    # ### end Alembic commands ###
